version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php
 
  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - db
 
  db:
    image: mariadb:10.7
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: testdb
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    volumes:
      - db-data:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306  

  phpmyadmin:
    image: phpmyadmin:5.2
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8888:80
    volumes:
    - phpmyadmin-data:/sessions
volumes:
  db-data:
  phpmyadmin-data: